version: '3'
services:
  nginx:
    image: nginx:1.17.10
    container_name: ng01
    ports:
      - '5500:5500'
    volumes:
      - ./src/frontend:/src
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  web:
    build: .
    container_name: dg01
    ports:
      - '8000:8000'
    command: bash -c "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      gunicorn app.wsgi:application -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src/backend:/src

  db:
    image: postgres:12.2
    ports:
      - "5432:5432" 
    container_name: ps01
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin